/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistrictsIndexRouteImport } from './routes/districts/index'
import { Route as PartyPartyIdRouteImport } from './routes/party/$partyId'
import { Route as DistrictsDistrictIdRouteImport } from './routes/districts/$districtId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsIndexRoute = DistrictsIndexRouteImport.update({
  id: '/districts/',
  path: '/districts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdRoute = PartyPartyIdRouteImport.update({
  id: '/party/$partyId',
  path: '/party/$partyId',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsDistrictIdRoute = DistrictsDistrictIdRouteImport.update({
  id: '/districts/$districtId',
  path: '/districts/$districtId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/districts/': typeof DistrictsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/districts': typeof DistrictsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/districts/': typeof DistrictsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/districts/$districtId' | '/party/$partyId' | '/districts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/districts/$districtId' | '/party/$partyId' | '/districts'
  id:
    | '__root__'
    | '/'
    | '/districts/$districtId'
    | '/party/$partyId'
    | '/districts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistrictsDistrictIdRoute: typeof DistrictsDistrictIdRoute
  PartyPartyIdRoute: typeof PartyPartyIdRoute
  DistrictsIndexRoute: typeof DistrictsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/': {
      id: '/districts/'
      path: '/districts'
      fullPath: '/districts/'
      preLoaderRoute: typeof DistrictsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$partyId': {
      id: '/party/$partyId'
      path: '/party/$partyId'
      fullPath: '/party/$partyId'
      preLoaderRoute: typeof PartyPartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/$districtId': {
      id: '/districts/$districtId'
      path: '/districts/$districtId'
      fullPath: '/districts/$districtId'
      preLoaderRoute: typeof DistrictsDistrictIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistrictsDistrictIdRoute: DistrictsDistrictIdRoute,
  PartyPartyIdRoute: PartyPartyIdRoute,
  DistrictsIndexRoute: DistrictsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
